### ISSUE TITLE
quick photo mode

### ISSUE THREAD

**Issue by test2a** [Ethereal-Developers-Inc/OpenScan#13]
right now if i have to say take 10 photos, i start with one, click on shutter. then i am taken to crop. i accept that. then i click on capture again.

can we improve on this workflow? i am suggesting creating a quick photo mode whereby i can set the defaults like crop and color and orientation and such once and then just click away. this is because if i want to take pictures of 10,20 or even more then current workflow is too tiring because there are steps that can be cut. 

also, one can use some sort of jig to hold the phone and then the current workflow brings in too much touching the screen. i am thinking setup once and then click on shutter to take as many photos. 

something like those book scanning rigs where you have a shutter button and the user just flips a page, click, flip, click.

**Comment by veejayts** [comment]
Quick scan feature has been implemented in the alpha version 2.0 (development_v2.0.0 branch) of this app.
