### ISSUE TITLE
borderless output

### ISSUE THREAD

**Issue by test2a** [Ethereal-Developers-Inc/OpenScan#14]
currently every pdf output has a white border.

would it be possible to have borderless output because the white border does not "feel" nice.

**Comment by veejayts** [comment]
Will be fixed in the next update

**Comment by jw243** [comment]
Any indication, when the next update will be due?
I would be so greatful if pdfs could be saved without this white border.
Thanks a lot!

**Comment by veejayts** [comment]
We are currently involved in a few other projects which is making it difficult to focus on OpenScan. We will try our best to fix a few bugs, remove borders from the PDFs and create a minor update.

**Comment by 5lttrz** [comment]
@veejayts Any plans on adding this in the next update?

**Comment by 5lttrz** [comment]
@vikram0230 any updates on this?

**Comment by veejayts** [comment]
The borders are only 5px in the latest version, are you requesting completely borderless output?

**Comment by 5lttrz** [comment]
Yes, that would be a good option to have
