### ISSUE TITLE
pdf export options

### ISSUE THREAD

**Issue by test2a** [Ethereal-Developers-Inc/OpenScan#15]
Libreoffice has this nice feature on pdf export

https://help.libreoffice.org/7.0/en-US/text/shared/01/ref_pdf_export_general.html?&DbPAR=WRITER&System=UNIX

including page range, image resolutions and sign with watermark. 

With regards to watermark, openscan does not add any watermark to the output, which is fine but that should not mean users should not be also allowed to not add one. say i want to write "confidential" to the output. i should be able to.

same for image resolutions. currently whatever resolutions is decided by the app is set and the output usually balloons to very high sizes. giving the user freedom to choose whatever quality/compression is suitable for them should be enabled.

same for the page range. say i take 10 photos but i want to export 1-7, and 4-8, or 1-9 and 1-10. i should be able to do that

**Comment by veejayts** [comment]
Implemented in v2.0.0
