### ISSUE TITLE
license

### ISSUE THREAD

**Issue by test2a** [Ethereal-Developers-Inc/OpenScan#16]
i am not sure if i should be writing this here but the current license is "MIT" as per github license page. i wonder if the permissive license was selected specifically or just willy nilly because this license gives a third party, anyone permission to use your work in their commercial closed source versions without open sourcing their version. 
GPL on the other hand forces a fork or a third party to also open source their version.

essentially if you are doing work for the community, there should not be a time when some unscrupulous persons would take your code, repackage it and sell it without contributing to the community.

 If the developers are fine with this arrangement and have done so on their own volition, fine but if not then they should seriously look at GPL 3. ;-)

**Comment by veejayts** [comment]
We were aware of the license. But your suggestion is noted.
