### ISSUE TITLE
Zoom bug

### ISSUE THREAD

**Issue by test2a** [Ethereal-Developers-Inc/OpenScan#21]
Got the updated app from play store as f droid would take time and all. Anyways I am very happy with the results. I just found two ish bugs.

This one is when I am viewing a page, I can zoom but it resets to original scale if I move fingers away from screen.

Zooming to any level should keep photo at that level until I zoom back manually.
I am having to hold fingers in a pinch position to read a text because removing fingers resets zoom

**Comment by veejayts** [comment]
This was implemented as a feature for ease of use.
