### ISSUE TITLE
Bug. Photos taken in app show up in camera folder in gallery

### ISSUE THREAD

**Issue by test2a** [Ethereal-Developers-Inc/OpenScan#23]
Any photos of pdfs I take are currently stored in camera roll as normal photos. Then I am having to delete all.
Either dont save photos because a user expects to use then in pdf has already done that, double work to delete them again. Or,  put then in a separate folder

**Comment by veejayts** [comment]
Could you specify what device, android version and gallery app you are using? We haven't experienced this when tested on multiple devices.

**Comment by test2a** [comment]
OK. Android 8.
/storage/emulated/0/DCIM/Camera
Here photos taken in open scan are saved.
Using simple gallery from f droid.

**Comment by VasilisKos** [comment]
This happens in Nokia 6.2 too, with stock Android 10, and Simple Gallery.

**Comment by vikram0230** [comment]
Fixed it the new release. Reopen if the issue exists.

**Comment by VasilisKos** [comment]
The issue is still there in the new 2.1 release.

**Comment by test2a** [comment]
yes. i confirm the same. I removed the old and installed fresh and saw photos i took in the app for making a pdf show up in camera gallery
