### ISSUE TITLE
𝙊𝙥𝙩𝙞𝙤𝙣 𝙤𝙛 𝙘𝙝𝙤𝙤𝙨𝙞𝙣𝙜 𝙢𝙤𝙧𝙚 𝙩𝙝𝙖𝙣 𝙤𝙣𝙚 𝙥𝙝𝙤𝙩𝙤 𝙖𝙩 𝙖 𝙩𝙞𝙢𝙚

### ISSUE THREAD

**Issue by shouyou10** [Ethereal-Developers-Inc/OpenScan#24]
𝘐 𝘢𝘮 𝘳𝘦𝘢𝘭𝘭𝘺 𝘪𝘮𝘱𝘳𝘦𝘴𝘴𝘦𝘥 𝘸𝘪𝘵𝘩 𝘵𝘩𝘦 𝘢𝘱𝘱. 𝘖𝘯𝘦 𝘰𝘧 𝘮𝘺 𝘵𝘸𝘰 𝘪𝘴𝘴𝘶𝘦𝘴 𝘸𝘪𝘵𝘩 𝘪𝘵 𝘪𝘴 𝘐 𝘢𝘮 𝘶𝘯𝘢𝘣𝘭𝘦 𝘵𝘰 𝘱𝘪𝘤𝘬 𝘮𝘰𝘳𝘦 𝘵𝘩𝘢𝘯 𝘰𝘯𝘦 𝘱𝘩𝘰𝘵𝘰 𝘢𝘵 𝘢 𝘵𝘪𝘮𝘦. 𝘛𝘩𝘪𝘴 𝘱𝘳𝘰𝘭𝘰𝘯𝘨𝘴 𝘵𝘩𝘦 𝘢𝘮𝘰𝘶𝘯𝘵 𝘰𝘧 𝘵𝘪𝘮𝘦 𝘭𝘰𝘢𝘥𝘪𝘯𝘨 𝘢𝘭𝘭 𝘵𝘩𝘦 𝘱𝘩𝘰𝘵𝘰𝘴. 𝘐𝘴 𝘪𝘵 𝘱𝘰𝘴𝘴𝘪𝘣𝘭𝘦 𝘵𝘰 𝘭𝘰𝘢𝘥 𝘮𝘰𝘳𝘦 𝘵𝘩𝘢𝘯 𝘢 𝘴𝘪𝘯𝘨𝘭𝘦 𝘱𝘩𝘰𝘵𝘰 𝘢𝘵 𝘢 𝘵𝘪𝘮𝘦?

**Comment by sc911** [comment]
Was just about to open an issue for that.
This would be a really great feature but I'm not sure if this isn't an OS issue/limitation, as I've seen this in other apps to.
Device: Google Pixel 3a, Android 11
App: from play store, version 2.0.0

**Comment by veejayts** [comment]
Updated in the latest release.
