### ISSUE TITLE
[Feature] markup /annotations

### ISSUE THREAD

**Issue by test2a** [Ethereal-Developers-Inc/OpenScan#30]
There are scanner apps that allow annotations support. Annotations can be using arrows, pencil, highlighter, marker, boxes and such.

**Comment by veejayts** [comment]
Drawing on or manipulation of PDFs in general is difficult to achieve which is why even #14 was marked wontfix.

**Comment by test2a** [comment]
Cant you reuse a photo editor library to do that?
All android photo apps Foss or otherwise have some photo editing. Use that and many features would get built for this app. 
https://github.com/burhanrashid52/PhotoEditor
