### ISSUE TITLE
when mixing modes no new Images are saved

### ISSUE THREAD

**Issue by sc911** [Ethereal-Developers-Inc/OpenScan#34]
Using this app the first time I found this bug: I started with normal mode for the first page, than decided to switch to quick mode for the next pages. After that I had the expected number of images/pages but all of them where showing the first image. 
I tried this once again, taking two images on normal mode and than switching to quick mode which led to the first two images being as expected and the other one showing the second image.
Sticking with one mode everything works as expected.
Device: Google Pixel 3a, Android 11
App: from play store, version 2.0.0

**Comment by veejayts** [comment]
We noticed this bug after the release. Working on it.
