### ISSUE TITLE
Auto Crop-Suggestion

### ISSUE THREAD

**Issue by mubashir-rehman** [Ethereal-Developers-Inc/OpenScan#35]
Kindly add option for auto-cropping, if not already present. The following repo might help:
https://github.com/mars885/doc-skanner

**Comment by pcastela** [comment]
+1

**Comment by itsmeboy0** [comment]
@vikram0230 Any reason this was closed without a response? This doesn't seem to be fixed yet.

**Comment by itsmeboy0** [comment]
Additional Info: [OpenNoteScanner](https://github.com/allgood/OpenNoteScanner) does this too, so it shouldn't be that hard.

**Comment by vikram0230** [comment]
@itsmeboy0  This feature has been implemented in the previous versions. We are working to enhance it.

**Comment by mubashir-rehman** [comment]
@vikram0230 then it should have been closed with implemented or invalid tag. btw thanks for confirmation.

**Comment by Sturm0** [comment]
I don't know how to enable auto cropping or it doesn't work.

![Image](https://github.com/user-attachments/assets/c233c7e7-d2a1-4ff5-b818-91d4458b6167)
I'm using the version from f-droid "IzzyOnDroid F-Droid repo"
