### ISSUE TITLE
Custom cropper screen 

### ISSUE THREAD

**Issue by UlanNurmatov** [Ethereal-Developers-Inc/OpenScan#36]
How can I remove 'Original' 'Magic Color' and other buttons from cropping screen? 
I've downloaded the Flutter scanner plugin and tried to modify -> scanner_core -> scanlibrary -> src -> main -> res -> layout -> result_layout.xml
but the buttons are still there.

**Comment by veejayts** [comment]
The repo present at [flutter-scanner-croppper](https://github.com/Ethereal-Developers-Inc/flutter-scanner-plugin) is just the API for dart to interact with the java code. The pub package manager unfortunately doesn't automatically fetch the local library dependencies in flutter. The [scanner_core/](https://github.com/Ethereal-Developers-Inc/flutter-scanner-plugin/tree/master/scanner_core/scanlibrary) is present for testing and reference purposes should anyone want to change the plugin API.

If you want to make any changes to the scanner, all the code lives at [OpenScan/android/scanlibrary/](https://github.com/Ethereal-Developers-Inc/OpenScan/tree/master/android/scanlibrary).

To remove the buttons, I suppose you would have to make changes in these files:
- [OpenScan/android/scanlibrary/src/main/java/com/scanlibrary/ResultFragment.java](https://github.com/Ethereal-Developers-Inc/OpenScan/blob/master/android/scanlibrary/src/main/java/com/scanlibrary/ResultFragment.java)
- [OpenScan/android/scanlibrary/src/main/res/layout/result_layout.xml](https://github.com/Ethereal-Developers-Inc/OpenScan/blob/master/android/scanlibrary/src/main/res/layout/result_layout.xml)

**Comment by UlanNurmatov** [comment]
Thanks, I removed the buttons. But when I click the the empty button areas, I get this printed:
V/Scanning(18090): Scaning getPoints
V/Scanning(18090): Scaning size() 2

Does it mean that button functions still run when clicked?

**Comment by veejayts** [comment]
Those logs have to do with the perspective cropping.

**Comment by veejayts** [comment]
Closing this issue. Ping here if you run into any problems regarding this.
