### ISSUE TITLE
App size 

### ISSUE THREAD

**Issue by UlanNurmatov** [Ethereal-Developers-Inc/OpenScan#38]
Hi. Thanks for quick responses. One more question:

After installing the app in release mode on:
Redmi 4A (mobile) • android-arm64 • Android 7.1.2 (API 25)
Android SDK built for x86 64 (mobile) • emulator-5554 • android-x64   • Android 10 (API 29) (emulator)
The app size is around 77Mb. 
Is it normal size? Any ways to reduce the size? 
Thank you

**Comment by veejayts** [comment]
Is it the apk size or the app size? The apk size is ~70mb if you don't split it for each arch (i.e. you get the fat apk). To get the separate apks, you would have to run `flutter build apk --split-per-abi`.

**Comment by UlanNurmatov** [comment]
It's the app size when I install it by` flutter run --release`
When I run `flutter build apk --split-per-abi` and drag the apk into the emulator, the app size is 50mb. 
Still not much smaller.

**Comment by veejayts** [comment]
App size is generally ~40mb. Maybe because its emulator its occupying some extra space.
