### ISSUE TITLE
Directly using the "PDF" button does nothing; "Export" > "Save to device" in menu never finishes

### ISSUE THREAD

**Issue by JayFoxRox** [Ethereal-Developers-Inc/OpenScan#41]
What the title says: PDF button in frontend does appear to do absolutely nothing (except blink), when being clicked on.
The context menu entry "Export" &rarr; "Save to device" never finishes the "Selected directory" step (remains on swirl animation).

I suspect this has to do with this phone (Samsung S3 Mini) running an old lineageos without some of the necessary Google services?
Even then, these actions should fail more gracefully.

I'm also not sure where output images are stored, prior to export (Currently I try to take them directly from data/*openscan/files/, but this is also prevented by unrelated issue #37 - it also feels like a hack to grab them from that folder).

**Comment by veejayts** [comment]
Reopen if the issue persists
