### ISSUE TITLE
Quick Scan orientation not working compared to Normal Scan

### ISSUE THREAD

**Issue by PunkmeisterDuy** [Ethereal-Developers-Inc/OpenScan#47]
Whenever I do a quick scan vertically, it scans it horizontally compared to using Normal scan. 
Sometimes the quick scan works, but most of the time it scans horizontally

Phone: s10e
Android 11

**Comment by vikram0230** [comment]
We were unable reproduce this issue. Reopen if this issue exists in the new release.
