### ISSUE TITLE
Translations

### ISSUE THREAD

**Issue by VasilisKos** [Ethereal-Developers-Inc/OpenScan#52]
I looked in the folder (values) where usually translation string files are, but I didn't find any. How about adding one, and make translations possible? I'm ready to translate it in Greek! ☺️

**Comment by vikram0230** [comment]
You are welcome to do the translations  ;)
As arb file on [dev_v3](https://github.com/Ethereal-Developers-Inc/OpenScan/tree/dev_v3) branch, use [app_en.arb](https://github.com/Ethereal-Developers-Inc/OpenScan/blob/dev_v3/lib/l10n/app_en.arb) as reference.

**Comment by VasilisKos** [comment]
I finished the Greek translation but it seems I messed up things a little
bit on GitHub. Can you please check?

Στις Παρ, 6 Μαΐ 2022, 18:57 ο χρήστης Vikram Harikrishnan <
***@***.***> έγραψε:

**Comment by veejayts** [comment]
Your branch is forked from dev_v3 branch but the PR is requesting to merge into master. Please give the PR to the dev_v3 branch as @vikram0230 requested.
