### ISSUE TITLE
Rotate Image Quality bug

### ISSUE THREAD

**Issue by 5lttrz** [Ethereal-Developers-Inc/OpenScan#58]
Issue: Scanned Image when rotated reduces in quality

Steps to reproduce:

- Use OpenScan Quick or Normal Scan to scan an image/page
(Note: For main cause of user experiencing this issue. See Issue #59)

- Rotate the Landscape image into potrait by using the Crop option from the Page menu.

- Quality of text or handwriting reduces

Device: Samsung Galaxy M21

**Comment by veejayts** [comment]
We have improved image quality in the v2.2.0 update. Feel free to reopen if the issue persists.
