### ISSUE TITLE
app crashes on taking multiple photos

### ISSUE THREAD

**Issue by test2a** [Ethereal-Developers-Inc/OpenScan#6]
hi. 
i have installed the app on xiaomi mi pad 1 running android 4.4.4 and the app is working fine as long as i take a single photo at once. 
if i take say 3 photos, the app crashes and all saved data is gone. What i am doing now is, i am taking a photo, clicking on back. then from sidebar add image.
then take a photo, then back to home and then open the folder again. it is time consuming but that is only how i am able to manage using the app. 
Other than that, you are doing a great job. I will be helping in bug reporting and such

**Comment by vikram0230** [comment]
We are working on that issue. Can expect an update in a month.
Thanks for your support!
