### ISSUE TITLE
Inconsistent cropping and PDF page size

### ISSUE THREAD

**Issue by 5lttrz** [Ethereal-Developers-Inc/OpenScan#60]
Issue1 : Cropping causes white borders to appear around the page/document in the PDF file

![Screenshot_20210822-124123_MiXplorer.png](https://user-images.githubusercontent.com/75839799/130346060-6431cacd-d6bb-4e3d-a6a3-31f0813657cb.png)

Issue2 : Inconsistent page sizes in PDF

![Screenshot_20210822-124226_MiXplorer.png](https://user-images.githubusercontent.com/75839799/130346086-f4d93f25-04cc-4114-9903-0bba6bd26681.png)

Possible Fix: Make page of PDF file to resize to the dimensions of scanned and/or cropped document.

**Comment by veejayts** [comment]
Feel free to reopen if this issue persists after recent v2.2.0 update
