### ISSUE TITLE
Generic icons in app icon shortcuts

### ISSUE THREAD

**Issue by VasilisKos** [Ethereal-Developers-Inc/OpenScan#61]
The icons in the 3 app icon long tap shortcuts are the generic Android ones. I guess something else was meant to be there? 🤔

![Screenshot_20210824-102924](https://user-images.githubusercontent.com/12777771/130575725-b55d0db8-6286-4484-a3bc-d0dcab2d8cbd.png)

**Comment by veejayts** [comment]
Yeah! We assigned icons to those quick actions.

**Comment by VasilisKos** [comment]
> Yeah! We assigned icons to those quick actions.

Guess they're those in the FAB? They should be.

![Screenshot_20210824-222812](https://user-images.githubusercontent.com/12777771/130678048-40555815-18bd-4cfa-9578-0fdbd634a051.png)

**Comment by veejayts** [comment]
We're using a package to get this done. We customized these icons and placed them in the android asset images. We'll have to look into why this isn't being picked up properly. FAB icons are different.

Thanks for reporting!

**Comment by veejayts** [comment]
This is fixed in v2.2.0 update. Feel free to reopen if the issue persists.
