### ISSUE TITLE
Increase PDF compression

### ISSUE THREAD

**Issue by user8446** [Ethereal-Developers-Inc/OpenScan#65]
Hello,

In setting the export quality to "low", a scanned receipt will still be approx. a 2.3mb pdf. Judging by other receipt scan type apps, the pdf's are under 200k while still retaining a good quality picture for a document. 
It would be a huge improvement to increase the compression or have an additional quality setting for higher compression. At approx 2.3mb per pdf, OpenScan is not usable for a receipt/document app (at 200k you could take 11 scans with the same storage as one OpenScan pdf)

Thank you for the consideration and development!

**Comment by veejayts** [comment]
Feel free to reopen if this issue still persists after v2.2.0 update
