### ISSUE TITLE
allow using photos from gallery

### ISSUE THREAD

**Issue by test2a** [Ethereal-Developers-Inc/OpenScan#7]
currently the only way to use the app is to take fresh photos. My suggestion is to allow saved photos in gallery etc to be added to a document.

**Comment by shubham-chhimpa** [comment]
assign this issue to me.

**Comment by veejayts** [comment]
It's WIP. The back end is being overhauled which changes the way the images are interacted with.

**Comment by shubham-chhimpa** [comment]
I have completed it.... yesterday... so should i not create the PR?

**Comment by veejayts** [comment]
Implemented in the v2.0 release.
