### ISSUE TITLE
Where are the scans stored?

### ISSUE THREAD

**Issue by boozedog** [Ethereal-Developers-Inc/OpenScan#75]
I'd like to sync my scans with syncthing but I can't find where the PDFs are being stored on my device.

**Comment by veejayts** [comment]
Under the Documents folder.
Documents -> OpenScan -> PDF

**Comment by boozedog** [comment]
@veejayts Very strange -- I've done a couple scans now and when I look in the Documents folder using the Files app, I only see one folder there from a different application. There's no OpenScan folder in my Documents folder.

**Comment by boozedog** [comment]
Is there a way to configure this in the OpenScan app itself?
