### ISSUE TITLE
Workaround if default camera app is undesired?

### ISSUE THREAD

**Issue by mirror176** [Ethereal-Developers-Inc/OpenScan#77]
Is the workflow alternative only to take picture in other camera app as image files, then open OpenScan and do "+>Import from Gallery" or are there other ways to go about it?
  I'm new on Android (starting on v12) devices but replaced the camera with OpenCamera (for now) for my camera use. Internet searching implies Google removed changing the default camera app due to location security concerns; ironically I set the default camera app to not function by denying it permissions that I thought didn't make sense to force (nearby devices). Is that correct that there is no workaround known to override the default this app will jump to?
  Now if I only found a way to crop images to page as easily as this app pulled it off but in image form then it would be easier for single page exchanges...
Thanks for the great program!

**Comment by vikram0230** [comment]
If your phone doesn't allow third party app as default, there wouldn't be a work-around except importing images from gallery.
OpenScan just opens the default camera app in the phone settings to capture images but it doesn't have the permission to choose which app to use.
