### ISSUE TITLE
Alternative Download

### ISSUE THREAD

**Issue by IzzySoft** [Ethereal-Developers-Inc/OpenScan#9]
Great to see a tracker-free FOSS PDF-scanner – thanks for that! Would you mind providing the APK to non-Google users (think: Google-free Huawei, LineageOS etc. devices) as well – e.g. by attaching it to the corresponding release tag? Thanks in advance!

**Comment by test2a** [comment]
@veejayts can you have the apk without the library and once installed, download it and then use it? just like how f-droid syncs the repos and stuff.

**Comment by IzzySoft** [comment]
That's basically what [Open Note Scanner](https://github.com/ctodobom/OpenNoteScanner) does at well. From the description of that app:

> In order to work, Open Note Scanner needs to have access to the OpenCV Manager application installed. If it could not find it, it will offer to download it from GitHub or Play Store. It is also possible to manualy install it from the OpenCV SDK for Android, available on http://opencv.org

Note that app is also available [at F-Droid](https://f-droid.org/packages/com.todobom.opennotescanner/).

**Comment by test2a** [comment]
@IzzySoft heh. never used open note scanner before. yep. that is what i am suggesting. this should bypass the size constraint of the stores. hope this app gets better and people have a good choice when it comes to phone scanning

**Comment by veejayts** [comment]
Well that does seem interesting. I will have to look into learning how to do that but no promises. Will resume development on this app in a week or so.

**Comment by IzzySoft** [comment]
Yeah, that's the idea. Further, why have it included (unchanged) **with each update** if there's a more elegant way to deal with it? Btw: I haven't used that app either (lazyness and, admittedly, skepsis as for downloading a dependency "from somewhere else"). For the latter reason, it's good to have a corresponding hint in the app's description (that it downloads that library when not already installed, what it's for and why it's safe to do so)…

TBH, I'd feel much better about that library if it where available at F-Droid and would be fetched from there. But as it's not an app, I guess the client cannot handle that, unfortunately.

**Comment by veejayts** [comment]
Agreed, you make valid points. One of the reasons I am hesitant about making the user download content/code from external sources is because I don't want to even accidentally compromise the users privacy. I know that is a little paranoid, but I would rather larger file size than compromised privacy. Plus it would mean more work to maintain it.

**Comment by test2a** [comment]
one suggestion. the app currently works fine "as is". So, how about for getting improved functionality once the user is using the app, it can suggest to download the package from a direct link which would be on github, unlike the open note scanner app earlier mentioned which refuses to work without the package.

**Comment by IzzySoft** [comment]
Good idea: Deploy the app with "base functionality" and leave it to the user to pull in OpenCV for "advanced functionality".

To top that: unless/until OpenCV is available from a "trusted source" like F-Droid, to lower the barrier you could include it with your repo here *as git submodule* – which leaves you in control as you are now: the submodule points to a specific commit in the OpenCV repository, leaving it up to you which version will be fetched – while the user sees it comes from your repo (so if they trust you with your app, they can also trust you with this).

**Comment by IzzySoft** [comment]
Just a small heads-up including best new-year wishes – and the gentle question if there are news on this topic?

**Comment by veejayts** [comment]
A happy new year to you too! Finalizing and updating the 2.0 release right now. Do let me know if any assistance is required from my end for the release.

**Comment by IzzySoft** [comment]
Thanks a lot! Your app will become [available here](https://apt.izzysoft.de/fdroid/index/apk/com.ethereal.openscan) with the next sync in about 5.5h :smiley:

If you want to apply for listing at F-Droid.org, your app will certainly be welcome there as well. Should you need help with that, I'll be available there.
